Revert "Update plugin.py"
This reverts commit 5e928ec56dc024d73db3e412a8353c19bf374b4d.

Commit reverted as it breaks OpenViX (even though you said it didn't).

< 363.1806> Traceback (most recent call last):
< 363.1808> File "/usr/lib/enigma2/python/Components/ActionMap.py", line 60, in action
< 363.1829> File "/usr/lib/enigma2/python/Plugins/Extensions/EPGTranslator/plugin.py", line 1085, in EPGTr_ToggleMode
< 363.1876> self.setEvent(self.event)
< 363.1878> File "/usr/lib/enigma2/python/Plugins/Extensions/EPGTranslator/plugin.py", line 1120, in My_setEvent
< 363.1927> uref = make_uref(event.getEventId(), self.serviceRef.getServiceName())
< 363.1931> AttributeError: 'EventViewEPGSelect' object has no attribute 'serviceRef'

The cause of the original crash is due to a change of variable name in OpenATV EventView.

This needs fixing in OpenATV enigma, not here.

https://github.com/openatv/enigma2/commit/c3c0fb35312f20358670710ebe8e8cd8d0b45de3#diff-b150fe1a6b86445b87508a3a0639cf845aeaa17a8e6c64d5a68a362dad10a006L32