[WebKitHbbTV] Py3 does not have str.decode()
Commenting this out shows no negative effect for me (but this must have been here for a reason).

<   155.4218> 13:06:38.7771 Traceback (most recent call last):
<   155.4219> 13:06:38.7772   File "/usr/lib/enigma2/python/Navigation.py", line 93, in dispatchEvent
<   155.4225> 13:06:38.7778     x(i)
<   155.4226> 13:06:38.7779   File "/usr/lib/enigma2/python/Components/ServiceEventTracker.py", line 85, in event
<   155.4236> 13:06:38.7789     func[2]()
<   155.4237> 13:06:38.7789   File "/usr/lib/enigma2/python/Plugins/Extensions/WebkitHbbTV/plugin.py", line 259, in _cb_ait_detected
<   155.4248> 13:06:38.7800     self._app_info = self.get_autostart_application()
<   155.4248> 13:06:38.7801   File "/usr/lib/enigma2/python/Plugins/Extensions/WebkitHbbTV/plugin.py", line 312, in get_autostart_application
<   155.4254> 13:06:38.7807     if reader.doOpen(info, self.m_vuplus):
<   155.4255> 13:06:38.7807   File "/usr/lib/enigma2/python/Plugins/Extensions/WebkitHbbTV/aitreader.py", line 94, in doOpen
<   155.4258> 13:06:38.7810     document = document.decode("cp1252").encode("utf-8")
<   155.4259> 13:06:38.7811 AttributeError: 'str' object has no attribute 'decode'